# List vs Array

# Numpy

In [1]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]
print(type(my_list))

<class 'list'>


In [5]:
arr=np.array(my_list)
print(type(arr))


<class 'numpy.ndarray'>


In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape

(5,)

In [11]:
#multinested array
my_list1=[1,2,3]
my_list2=[3,4,5]
my_list3=[6,7,8]
arr=np.array([my_list1,my_list2,my_list3])

In [12]:
arr.shape

(3, 3)

# reshape

In [17]:
my_list1=[1,2,3]
my_list2=[3,4,5]
arr=np.array([my_list1,my_list2])


array([[1, 2],
       [3, 3],
       [4, 5]])

In [21]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [19]:
arr.shape

(2, 3)

In [20]:
arr.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

# arrange

In [22]:
arr=np.arange(0,10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[3:]=100

In [25]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

# linespace

In [31]:
np.linspace(1,10,50)#equally spaced

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
len(np.linspace(1,10,50))

50

# copy

In [40]:
arr1=np.array([1,2,3,4,4,4,4,4,4])
arr2=arr1

#here arr2 is just a reference variable so any change u make in arr2 will also reflect in arr1

In [41]:
arr2[3:]=5

In [42]:
arr2

array([1, 2, 3, 5, 5, 5, 5, 5, 5])

In [43]:
arr1

array([1, 2, 3, 5, 5, 5, 5, 5, 5])

In [45]:


#to avoid that use copy
arr1=np.array([1,2,3,4,4,4,4,4,4])
arr2=arr1.copy()

arr1

array([1, 2, 3, 4, 4, 4, 4, 4, 4])

In [46]:
arr2

array([1, 2, 3, 4, 4, 4, 4, 4, 4])

In [47]:
arr2<2

array([ True, False, False, False, False, False, False, False, False])

In [48]:
arr2*2

array([2, 4, 6, 8, 8, 8, 8, 8, 8])

# create array and reshape

In [49]:
arr1=np.arange(0,10).reshape(2,5) 

In [50]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# random distribution but standard normal 

In [51]:

np.random.randn(4,4)

array([[ 1.34022641,  1.13610218, -0.47276437, -0.95184101],
       [-1.59627786,  1.40867655,  0.58313145,  0.98469523],
       [ 0.17106179, -1.26746067, -0.66249416,  1.36042061],
       [-0.22671738, -0.36264675, -0.90648552,  0.44136672]])